import chroma from "chroma-js";
import { createColorTheme } from "./schema";

const colortheme = createColorTheme({
  ABSTRACT: "lightgrey",
  ARTICLE_HEADER_CLIPPED: "mediumseagreen",
  ARTICLE_HEADER_NOT_CLIPPED: "orange",
  BACKGROUNDCOVER_CLIPPED: "rgba(0,0,0,0.7)",
  BACKGROUNDCOVER_NOT_CLIPPED: "rgba(0,0,0,0.5)",
  CLIPBUTTON_CLIPPED_BACKGROUND: "mediumseagreen",
  CLIPBUTTON_CLIPPED_TEXT: "ghostwhite",
  CLIPBUTTON_NOT_CLIPPED_BACKGROUND: "orange",
  CLIPBUTTON_NOT_CLIPPED_TEXT: "white",
  LOADINGARTICLE_BACKGROUND: "white",
  LOADINGARTICLE_CIRCLE: "black",
  LOADINGRESULT_BACKGROUND: "black",
  LOADINGRESULT_CIRCLE: "black",
  NOCLIPPED_BACKGROUND: chroma("mediumseagreen").alpha(0.2).hex(),
  NOCLIPPED_TEXT: "black",
  NORESULT_BACKGROUND: chroma("orange").alpha(0.2).hex(),
  NORESULT_TEXT: "black",
  PAGE_CONTAINER: "white",
  PAGE_HEADER_CLIPPED: "mediumseagreen",
  PAGE_HEADER_NOT_CLIPPED: "orange",
  PUB_DATE: "white",
  RECENTQUERY_BACKGROUND: "white",
  RECENTQUERY_BORDER: "grey",
  RECENTQUERY_DELETE: "white",
  RECENTQUERY_DELETE_BACKGROUND: "tomato",
  RECENTQUERY_DELETE_BORDER: "brick",
  RECENTQUERY_TEXT: "black",
  SEARCHBAR_BACKGROUND: "white",
  SEARCHBAR_BORDER: "grey",
  SEARCHBAR_PLACEHOLDER: "black",
  SEARCHBAR_TEXT: "black",
  SEARCHBUTTON_BACKGROUND: "orange",
  SEARCHBUTTON_ICON: "white",
  TAB_BACKGROUND: "ghostwhite",
  TAB_INDICATOR: "mediumseagreen",
  TAB_TEXT: "black",
  THEMETOGGLER_BACKGROUND: "lightgrey",
})

export default colortheme;